services:
  server:
    image: figuradocker/docker-express
    ports: 
      - 5050:5000
    command: npm run dev
    volumes: 
    - ./server/src/:/app/src/

  db:
    # platform: linux/amd64
    image: postgres:15
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d testDB -U postgres"]
      interval: 5s
      timeout: 40s
      retries: 15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: testDB
    ports:
      - 5432:5432
    volumes:
      - testDB-data:/var/lib/postgresql/data
volumes:
  testDB-data: